config/routes.rb
Rails.application.routes.draw do
  resources :incidents, only: [:new, :create, :show]
  
  root "home#index"
  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/incident.rb
class Incident < ApplicationRecord
	has_many :incident_kinds, inverse_of: :incident
	has_one :user_detail
	has_one :incident_location
	has_many :incident_files

	accepts_nested_attributes_for :incident_kinds, :user_detail, :incident_location, :incident_files

	validates_presence_of :description
end

app/models/incident_file.rb
class IncidentFile < ApplicationRecord
  belongs_to :incident

  has_attached_file :document,
  									default_url: "/images/:style/missing.png",
  									path: ":rails_root/public/incident_files/incident_:incident_id/:id.:extension"
  validates_attachment_content_type :document, content_type: /\Aimage/

  private

  Paperclip.interpolates :incident_id  do |attachment, style|
	  attachment.instance.incident_id
	end
end

app/models/incident_kind.rb
class IncidentKind < ApplicationRecord
	ALCOHOL = "alcohol".freeze
	BULLYING = "bullying".freeze
	HAZING = "hazing".freeze
	DRUGS = "drugs".freeze
	GRAFFITI = "graffiti".freeze
	INJURY = "injury".freeze
	SUSPICIOUS_ACTIVITY = "suspicious_activity".freeze
	TRESPASSING = "trespassing".freeze
	VANDALISM = "vandalism".freeze
	WEAPONS_VIOLATION = "weapons_violation".freeze
	TECHNOLOGY_MISUSE = "technology_misuse".freeze
	OTHER = "other".freeze

	KINDS = [ALCOHOL, BULLYING, HAZING, DRUGS, GRAFFITI, INJURY, SUSPICIOUS_ACTIVITY, TRESPASSING, VANDALISM, WEAPONS_VIOLATION, TECHNOLOGY_MISUSE, OTHER].freeze

	enum kind: KINDS
  belongs_to :incident
end 

app/models/incident_location.rb
class IncidentLocation < ApplicationRecord
	SCHOOL = "school".freeze
	TRANSPORTATION = "transportation".freeze
	EVENT = "event".freeze
	OTHER = "other".freeze

	LOCATIONS = [SCHOOL, TRANSPORTATION, EVENT, OTHER]

	LOCATION_TXT = {
		SCHOOL => "On school campuses and grounds",
		TRANSPORTATION => "During transportation to and from school",
		EVENT => "At school-sponsored events",
		OTHER => "More details"
	}

	enum location: LOCATIONS
  belongs_to :incident
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
	STUDENT = "student".freeze
	TEACHER = "teacher".freeze
	OTHER_STAFF = "other_staff".freeze
	PARENT = "student_parent".freeze
	COMMUNITY_MEMBER = "community_member".freeze

	ROLES = [STUDENT, TEACHER, OTHER_STAFF, PARENT, COMMUNITY_MEMBER]

	enum role: ROLES
  belongs_to :incident
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	redirect_to new_incident_path
  end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]

  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.all
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = session[:incident].present? ? Incident.new(session[:incident]) : Incident.new
    @incident.save if session[:incident].present?
    @detailed_form = params[:ft] == "detail"
    session.delete(:incident)
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)

    respond_to do |format|
      if @incident.save
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render :show, status: :created, location: @incident }
      else
        session[:incident] = @incident
        to_url = params[:ft] == "detail" ? new_incident_path(ft: params[:ft]) : new_incident_path

        format.html { redirect_to to_url }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url, notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      correct_files_params

      params.require(:incident).permit(
        :suspect_info, :witness_info, :occurred_at, :description,
        incident_kinds_attributes: [:kind],
        user_detail_attributes: [:name, :contact_info, :role],
        incident_location_attributes: [:location, :other_location],
        incident_files_attributes: [:document]
      )
    end

    # a little hack to support multiple files upload by normal file field upload way
    def correct_files_params
      files_arr = params[:incident].try(:[], :incident_files_attributes).nil? ? [] : params[:incident][:incident_files_attributes]["0"][:document].dup
      for i in 0..files_arr.length-1
        params[:incident][:incident_files_attributes][i.to_s] ||= {}
        params[:incident][:incident_files_attributes][i.to_s][:document] = files_arr[i]
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_incident_kind_name(kind)
		kind.capitalize.gsub("_", " ")
	end

	def get_user_role_name(role)
		role.capitalize.gsub("_", " ")
	end

	def get_location_name(loc)
		IncidentLocation::LOCATION_TXT[loc]
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_form.html.erb
<%= form_with(model: incident, local: true, html: {multipart: true}) do |form| %>
  <% if incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% incident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%if @detailed_form%>
    <div class="field">
      <span>Select type of incident:-</span>
      <br>

      <%IncidentKind::KINDS.each_with_index {|e, i|%>
        <%= form.fields_for :incident_kinds, IncidentKind.new, {child_index: i} do |f|%>
          <%#= f.collection_check_boxes  :kind, [[e]], :first, :last%>
          <span style="width: 5%; float: left;">
            <%= f.check_box :kind, {}, e, nil%>
            <%= f.label :kind, get_incident_kind_name(e)%>
          </span>
        <%end%>
      <%}%>
    </div>

    <div class="field">
      <span>Your details:-</span>
      <br>
      <%= check_box_tag :anonymous%>
      <%= label_tag :anonymous, "Report anonymously"%>


      <%= form.fields_for :user_detail, UserDetail.new do |f|%>
        <%= f.label :name%>
        <%= f.text_field :name, data: {field: "user_detail"}%>

        <%= f.label :contact_info%>
        <%= f.text_field :contact_info, data: {field: "user_detail"}%>

        <%= f.label :role, "Role:" %>
        <%= f.select :role, UserDetail::ROLES.map{|e| [get_user_role_name(e), e] }, {}, {data: {field: "user_detail"}} %>
      <%end%>
    </div>

    <div class="field">
      <%= form.fields_for :incident_location, IncidentLocation.new do |f|%>
        <%= f.label :location, "Location (select or provide details in other):" %>
        <%= f.select :location, IncidentLocation::LOCATIONS.map{|e| [get_location_name(e), e] }, {} %>

        <%= f.label :other_location, "Other location", data: {field: "location"}%>
        <%= f.text_field :other_location, data: {field: "location"}%>
      <%end%>
    </div>

    <div class="field">
      <%= form.label :suspect_info, "People involved:" %>
      <%= form.text_area :suspect_info %>
    </div>

    <div class="field">
      <%= form.label :witness_info, "Other observers if any:" %>
      <%= form.text_area :witness_info %>
    </div>

    <div class="field">
      <%= form.label :occurred_at %>
      <%= form.datetime_select :occurred_at %>
    </div>
  <%end%>

  <div class="field">
    <%= form.label :description, "Incident description:" %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.fields_for :incident_files, IncidentFile.new do |f|%>
      <%= f.label :document, "Attach files (select multiple by holding Ctrl when dialog box opens):" %>
      <%= f.file_field :document, {multiple: true} %>
    <%end%>
  </div>

  <div class="field">
    <%= hidden_field_tag 'ft', params[:ft]%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%if @detailed_form%>
  <%= link_to "Click here for simple form", new_incident_path%>
<%else%>
  <%= link_to "Click here for detailed form", new_incident_path(ft: "detail")%>
<%end%>


<script type="text/javascript">

  $("[data-field='location']").hide();
  $("#incident_incident_location_attributes_location").on("change", function(e){
    if($(this).val() == "other"){
      $("[data-field='location']").show();
    }else{
      $("[data-field='location']").val("").hide();
    }
  });


  $("#anonymous").on("change", function(e){
    if($(this).is(":checked")){
      $("[data-field='user_detail']").prop("disabled", true);
      $("input[data-field='user_detail']").val("");
      $("select[data-field='user_detail']").val("student");
    }else{
      $("[data-field='user_detail']").prop("disabled", false);
    }
  });

</script>

app/views/incidents/edit.html.erb
<h1>Editing Incident</h1>

<%= render 'form', incident: @incident %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Incidents</h1>

<table>
  <thead>
    <tr>
      <th>Suspect info</th>
      <th>Witness info</th>
      <th>Occurred at</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <td><%= incident.suspect_info %></td>
        <td><%= incident.witness_info %></td>
        <td><%= incident.occurred_at %></td>
        <td><%= incident.description %></td>
        <td><%= link_to 'Show', incident %></td>
        <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
        <td><%= link_to 'Destroy', incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incident', new_incident_path %>

app/views/incidents/new.html.erb
<%= render 'form', incident: @incident %>

app/views/incidents/show.html.erb
<p id="notice">Thank you for reporting an incident.</p>


<%= link_to 'Back to form', new_incident_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IncidentReportingTool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h2>Lincoln High School</h2>
    <h4>Incident Reporting Page</h4>
    <%= yield %>
  </body>
</html>